/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "../../packages/ui/src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        curiousbees: {
          blue: "#0C4DA2",
          gold: "#FFC828",
          crimson: "#800020",
          navy: "#0a192f",
          accent: "#B88608",
        },
        srm: {
          blue: "#0C4DA2",
          gold: "#FFC828",
          crimson: "#800020",
          navy: "#0a192f",
          accent: "#B88608",
        },
        // Premium ElevenLabs Design System Colors
        darkBg: "#f5f3f1",
        darkSurface: "#ffffff",
        darkSurfaceMuted: "#f7f4f2",
        darkPanel: "#1e1916",
        indigoElectric: "#6C63FF",
        violetRoyal: "#9B59B6",
        tealGlow: "#00C2B2",
        textPrimary: "#000000",
        textMuted: "#a59f97",
        textSecondary: "#6e6e6e",
        textTertiary: "#a59f97",
        textMutedDark: "#a59f97",
        dangerAlert: "#c00",
        borderStroke: "#e8e5e1",
        aiBlue: "#61b5db",
        
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",

        // Semantic tokens from requirements
        "surface-elevated": "#ffffff",
        "surface": "#fbf8ff",
        "muted": "#f4f2ff",

        // Stitch-specific colors
        "on-tertiary-fixed-variant": "#5d4200",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#251a00",
        "on-secondary-container": "#6f5400",
        "on-primary": "#ffffff",
        "tertiary": "#5e4300",
        "on-secondary-fixed-variant": "#5a4400",
        "on-primary-fixed-variant": "#004494",
        "surface-container": "#edecff",
        "surface-variant": "#e1e1f5",
        "secondary-fixed-dim": "#f5bf1c",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#191b29",
        "on-background": "#191b29",
        "tertiary-fixed": "#ffdea6",
        "surface-container-highest": "#e1e1f5",
        "primary-container": "#275db2",
        "surface-tint": "#265cb1",
        "on-tertiary-fixed": "#271900",
        "secondary": "#775a00",
        "error": "#ba1a1a",
        "surface-container-low": "#f4f2ff",
        "on-surface-variant": "#424654",
        "primary-fixed": "#d8e2ff",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#ffd384",
        "on-primary-fixed": "#001a41",
        "inverse-primary": "#adc6ff",
        "secondary-container": "#fec727",
        "on-error-container": "#93000a",
        "inverse-surface": "#2e2f3e",
        "surface-container-high": "#e6e6fa",
        "outline-variant": "#c3c6d6",
        "surface-dim": "#d8d8ec",
        "primary-fixed-dim": "#adc6ff",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#f7bd47",
        "surface-bright": "#fbf8ff",
        "tertiary-container": "#7c5900",
        "on-primary-container": "#cbdaff",
        "inverse-on-surface": "#f0efff",
        "primary": "#004495",
        "secondary-fixed": "#ffdf97",
        "outline": "#737785",
        "destructive": "#ba1a1a",

        // ── Semantic Status Tokens ────────────────────────────────────────
        "success":           "#1a7a4a",
        "success-container": "#d4f0e3",
        "on-success":        "#ffffff",
        "on-success-container": "#0a3d23",

        "warning":           "#8a5900",
        "warning-container": "#ffefc7",
        "on-warning":        "#ffffff",
        "on-warning-container": "#3d2800",

        "info":              "#0055cc",
        "info-container":    "#d6e4ff",
        "on-info":           "#ffffff",
        "on-info-container": "#002266",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        "unit": "4px",
        "container-max": "1440px",
        "gutter": "24px",
        "margin-desktop": "40px",
        "margin-tablet": "24px",
        "margin-mobile": "16px",
        "stack-xs": "4px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "stack-xl": "64px",
      },
      fontFamily: {
        sans: ["var(--font-sans)", "Inter", "Inter Fallback", "sans-serif"],
        display: ["var(--font-display)", "Waldenburg", "Waldenburg Fallback", "sans-serif"],
        mono: ["var(--font-mono)", "WaldenburgFH", "WaldenburgFH Fallback", "monospace"],
        "display-lg": ["Geist", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "headline-xl-mobile": ["Geist", "sans-serif"],
        "headline-xl": ["Geist", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-xl": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-xl-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "600" }],
      },
      animation: {
        "pulse-slow": "pulse-slow 8s ease-in-out infinite",
        "pulse-fast": "pulse-fast 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "marquee": "marquee 35s linear infinite",
        "flow": "flow 2s linear infinite",
        "shake": "shake 0.5s ease-in-out",
        "spin-slow": "spin 8s linear infinite",
      },
      keyframes: {
        "pulse-slow": {
          "0%, 100%": { transform: "scale(1) translate(0px, 0px)", opacity: 0.15 },
          "33%": { transform: "scale(1.15) translate(30px, -40px)", opacity: 0.22 },
          "66%": { transform: "scale(0.9) translate(-20px, 20px)", opacity: 0.18 },
        },
        "pulse-fast": {
          "0%, 100%": { opacity: 0.25, transform: "scale(1)" },
          "50%": { opacity: 0.7, transform: "scale(1.05)" },
        },
        "marquee": {
          "0%": { transform: "translateX(0%)" },
          "100%": { transform: "translateX(-50%)" },
        },
        "flow": {
          "0%": { "stroke-dashoffset": "20" },
          "100%": { "stroke-dashoffset": "0" },
        },
        "shake": {
          "0%, 100%": { transform: "rotate(0deg)" },
          "20%, 60%": { transform: "rotate(-10deg)" },
          "40%, 80%": { transform: "rotate(10deg)" },
        },
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}

